package com.example.Exception.practice;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collectors;

public class Exception4 {
    static List<Integer> list = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8));

//    void  validate(Object o){
//        if( bug bussiness){
//            throw new AppExcep("ko t")
//        }else if ( co loi validate){
//            return "asa";
//            throw  new ValidationException()
//        }
//    }
}
